apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: oawofolu/pgadmin4-base
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: test@test.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: alwaysbekind
        - name: PGADMIN_LISTEN_ADDRESS
          value: 0.0.0.0
