---
apiVersion: v1
kind: Secret
metadata:
  name: greenplum-binding-compatible
type: Opaque
stringData:
  type: $PGADMIN_GREENPLUM_TYPE
  provider: $PGADMIN_GREENPLUM_PROVIDER
  host: "$PGADMIN_GREENPLUM_HOST"
  port: "$PGADMIN_GREENPLUM_PORT"
  database: "$PGADMIN_GREENPLUM_DATABASE"
  username: "$PGADMIN_GREENPLUM_USERNAME"
  password: "$PGADMIN_GREENPLUM_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-binding-compatible
type: Opaque
stringData:
  type: $PGADMIN_POSTGRES_TYPE
  provider: $PGADMIN_POSTGRES_PROVIDER
  host: "$PGADMIN_POSTGRES_HOST"
  port: "$PGADMIN_POSTGRES_PORT"
  database: "$PGADMIN_POSTGRES_DATABASE"
  username: "$PGADMIN_POSTGRES_USERNAME"
  password: "$PGADMIN_POSTGRES_PASSWORD"